### ISSUE TITLE
Enable in vim insert mode

### ISSUE THREAD

**Issue by tdhopper** [mattgreen/park.fish#1]
To enable in Vim insert mode, I had to do `bind -M insert \cq '__park'`.

**Comment by mattgreen** [comment]
Would this need to be on in all vim modes?

I'm happy to throw this in, just wanted to poll what the most intuitive defaults would be.

**Comment by tdhopper** [comment]
@mattgreen I guess so. I'm not that familiar with customizing vim mode in fish.

**Comment by mattgreen** [comment]
Added in 5b63038c4e5af14d70ea779d8e3cb41600d594ae
